//
// Created by avsom on 9/25/2023.
//

#ifndef SIMULACRAENGINE_WIN32DEFINES_H
#define SIMULACRAENGINE_WIN32DEFINES_H

#endif //SIMULACRAENGINE_WIN32DEFINES_H

#define WIN32_WINDOW_CLASS_NAME "SimulacraEngine"