//
// Created by avsom on 12/9/2023.
//

#ifndef SIMULACRAENGINE_SIMULACRAVULKANPLATFORM_H
#define SIMULACRAENGINE_SIMULACRAVULKANPLATFORM_H


class SimulacraVulkanPlatform
{

};


#endif //SIMULACRAENGINE_SIMULACRAVULKANPLATFORM_H
