//
// Created by avsom on 10/22/2023.
//

#ifndef SIMULACRAENGINE_SIMULACRAPLATFORMS_H
#define SIMULACRAENGINE_SIMULACRAPLATFORMS_H

#if defined(WIN32)
    #define SIM_PLATFORM WIN32
#endif

#endif //SIMULACRAENGINE_SIMULACRAPLATFORMS_H

