//
// Created by avsom on 9/29/2023.
//

#ifndef SIMULACRAENGINE_DOUBLEENDEDSTACKALLOCATOR_H
#define SIMULACRAENGINE_DOUBLEENDEDSTACKALLOCATOR_H


class DoubleEndedStackAllocator
{

};


#endif //SIMULACRAENGINE_DOUBLEENDEDSTACKALLOCATOR_H
